services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ModuleTemplate\ProductVote\Dao\ProductVoteDaoInterface:
    class: OxidEsales\ModuleTemplate\ProductVote\Dao\ProductVoteDao
    public: true

  OxidEsales\ModuleTemplate\ProductVote\Dao\ResultDaoInterface:
    class: OxidEsales\ModuleTemplate\ProductVote\Dao\ResultDao
    public: true

  OxidEsales\ModuleTemplate\ProductVote\DataMapper\ProductVoteDataMapperInterface:
    class: OxidEsales\ModuleTemplate\ProductVote\DataMapper\ProductVoteDataMapper

  OxidEsales\ModuleTemplate\ProductVote\DataMapper\ResultDataMapperInterface:
    class: OxidEsales\ModuleTemplate\ProductVote\DataMapper\ResultDataMapper
